<?php
header('Content-type: application/pdf');
header('Content-Disposition: inline');
date_default_timezone_set('Asia/Jakarta');
$tgl_tagih = date('d/m/Y');
$tmp_tgl = date('Y-m-d');
$tgl_habis = date('d/m/Y', strtotime($tmp_tgl. ' + 3 days'));
$pdf_path = realpath(APPPATH . '../pdf_cache/');
$logo = realpath(APPPATH . '../img/omahlogo.png');
$this->fpdf->AddPage();
$this->fpdf->SetLeftMargin(20);
$this->fpdf->SetFont('Arial','B',24);
$this->fpdf->SetTextColor(0,153,87);
$this->fpdf->Image($logo,15);
$this->fpdf->ln();
//$this->fpdf->Cell(50,5,'OMAHIKLAN.COM',0,1,'L');
$this->fpdf->SetTextColor(0,0,0);
$this->fpdf->SetFont('Arial','B',15);
$this->fpdf->Cell(50,15,'Tagihan #'.$data_premium->ticket,0,1,'L');
$this->fpdf->SetFont('Times','',15);
$this->fpdf->Cell(50,10,'Tanggal cetak tagihan : '.$tgl_tagih,0,1,'L');
$this->fpdf->SetFont('Times','',15);
$this->fpdf->Cell(50,0.7,'Tanggal jatuh tempo : '.$tgl_habis,0,1,'L');
$this->fpdf->ln(25);

$this->fpdf->SetFont('Times','B',12);
$this->fpdf->Cell(50,0.7,'Ditagih ke ',0,1,'L');
$this->fpdf->ln(5);
$this->fpdf->SetFont('Times','',12);
$this->fpdf->Cell(50,0.7,$data_member->nama_depan." ".$data_member->nama_belakang,0,1,'L');
$this->fpdf->ln(5);
$this->fpdf->SetFont('Times','',12);
$this->fpdf->Cell(50,0.7,$data_member->alamat,0,1,'L');
$this->fpdf->ln(5);
$this->fpdf->SetFont('Times','',12);
$this->fpdf->Cell(50,0.7,$data_member->kota,0,1,'L');
$this->fpdf->ln(5);
$this->fpdf->SetFont('Times','',12);
$this->fpdf->Cell(50,0.7,$data_member->nama_toko,0,1,'L');
$this->fpdf->ln(25);

$this->fpdf->SetFont('Times','',12);
$this->fpdf->Cell(0,1,'Pembayaran paket premium 3 bulan : Rp 500,000,-',0,1,'C');

$this->fpdf->ln(25);
$this->fpdf->SetFont('Times','',12);
$this->fpdf->Cell(50,0.7,"Silahkan transfer ke salah satu rekening kami",0,1,'L');
$this->fpdf->ln(5);
$this->fpdf->SetFont('Times','',12);
$this->fpdf->Cell(50,0.7,"BNI : 0299778801",0,1,'L');
$this->fpdf->ln(5);
$this->fpdf->SetFont('Times','',12);
$this->fpdf->Cell(50,0.7,"BCA : 008781739093737",0,1,'L');
$this->fpdf->ln(5);
$this->fpdf->SetFont('Times','',12);
$this->fpdf->Cell(50,0.7,"a.n Aji Sulistyono",0,1,'L');

$this->fpdf->Output($pdf_path.'/'.$data_premium->ticket.'.pdf','F');
//$this->fpdf->Output($data_premium->ticket.'.pdf','I');
@readfile($pdf_path.'/'.$data_premium->ticket.'.pdf');
//echo $pdf_path.'ok.pdf';